/**
 * src/dsmath-extra.js — the extended discrete-maths bank.
 *
 * The original 54 curated cards in `src/dsmath-questions.js` stay exactly as
 * they were (their independent oracle in test/dsmath.test.js still recomputes
 * every one of them). This file is the bulk layer on top: the same nine topic
 * keys, so `!game dsmath hard counting` and every existing topic keyword keep
 * working, with midterm-2 areas (counting, relations, graphs, recurrences,
 * number theory, probability) carrying the most weight.
 *
 * ANSWER SAFETY
 * Numbers are never typed beside a question. Counting families call binom /
 * perm / starsBars, number theory calls gcd / lcm / phi / modPow, sequences
 * call fib / geomSum and the dice-and-card probabilities are
 * ENUMERATED from the sample space — a typo cannot become the answer, and the
 * generated cards are checked by test/banks.test.js.
 */

import {
    gcd, lcm, fact, binom, perm, starsBars, circularPerm, sumTo, sumSquares, sumCubes,
    phi, modPow, fib, arith, geom, geomSum, toBin, toHex, frac
} from './bank-tools.js';

const card = (topic, level, q, a, code) => ({ topic, level, q, a, ...(code ? { code } : {}) });
const easy = (topic, q, a, code) => card(topic, 'easy', q, a, code);
const hard = (topic, q, a, code) => card(topic, 'hard', q, a, code);
/** Leading accepted answer is computed; `extra` adds alternative spellings. */
/** Every accepted spelling is stringified, so a stray number cannot slip in raw. */
const num = (topic, level, q, value, ...extra) => card(topic, level, q, [...new Set([String(value), ...extra.map(String)])]);

// ─── enumerated sample spaces (no remembered probabilities) ──────────────────
const DIE = [1, 2, 3, 4, 5, 6];
const DICE = DIE.flatMap((a) => DIE.map((b) => [a, b]));
const COINS = ['H', 'T'];
const TOSS3 = COINS.flatMap((a) => COINS.flatMap((b) => COINS.map((c) => [a, b, c])));
const SUITS = ['S', 'H', 'D', 'C'];
const RANKS = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
const DECK = SUITS.flatMap((s) => RANKS.map((r) => [s, r]));
const countDice = (fn) => DICE.filter(fn).length;

export const DSMATH_EXTRA = Object.freeze([
    // ═══ Propositional & predicate logic ════════════════════════════════════
    easy('logic', 'What is the truth value of FALSE XOR FALSE?', ['false', 'f', '0']),
    easy('logic', 'What is the truth value of TRUE XOR TRUE?', ['false', 'f', '0']),
    easy('logic', 'What is the truth value of NOT TRUE?', ['false', 'f', '0']),
    easy('logic', 'Which connective is true exactly when both inputs are false?', ['nor', 'nor gate', 'neither']),
    easy('logic', 'Which connective is false exactly when both inputs are true?', ['nand', 'nand gate']),
    easy('logic', 'What is the truth value of TRUE → TRUE?', ['true', 't', '1']),
    easy('logic', 'What is the truth value of TRUE → FALSE?', ['false', 'f', '0']),
    easy('logic', 'What is the truth value of FALSE → FALSE?', ['true', 't', '1', 'vacuously true']),
    easy('logic', 'Which connective returns true when its two inputs differ?', ['xor', 'exclusive or', 'exclusive-or']),
    easy('logic', 'Which connective returns true when its two inputs agree?', ['xnor', 'biconditional', 'equivalence']),
    easy('logic', 'What is another name for the statement p ↔ q?', ['biconditional', 'equivalence', 'if and only if']),
    easy('logic', 'What is a statement that is always true called?', ['tautology', 'a tautology']),
    easy('logic', 'What is a statement that is never true called?', ['contradiction', 'a contradiction']),
    easy('logic', 'What is a statement that is neither a tautology nor a contradiction called?', ['contingency', 'contingent']),
    easy('logic', 'What is a statement containing variables whose truth depends on them called?', ['propositional function', 'predicate', 'open sentence']),
    easy('logic', 'Which symbol means "for all"?', ['∀', 'forall', 'universal quantifier']),
    easy('logic', 'Which symbol means "there exists"?', ['∃', 'exists', 'existential quantifier']),
    easy('logic', 'What is the negation of "all students passed"?', ['some student failed', 'at least one student failed', 'not all students passed']),
    easy('logic', 'Which law says NOT (p AND q) equals (NOT p) OR (NOT q)?', ['de morgan', 'de morgan’s law', "de morgan's law", 'demorgan']),
    hard('logic', 'What is the negation of ∀x P(x)?', ['∃x ¬p(x)', 'exists x not p(x)', '∃x ¬P(x)']),
    hard('logic', 'What is the negation of ∃x P(x)?', ['∀x ¬p(x)', 'for all x not p(x)', '∀x ¬P(x)']),
    hard('logic', 'What is the converse of p → q?', ['q → p', 'q -> p']),
    hard('logic', 'What is the inverse of p → q?', ['¬p → ¬q', 'not p implies not q', '¬p -> ¬q']),
    hard('logic', 'Which of converse, inverse or contrapositive is equivalent to p → q?', ['contrapositive', 'the contrapositive']),
    hard('logic', 'Is ∀x P(x) true or false when the domain is empty?', ['true', 'vacuously true']),
    hard('logic', 'Is ∃x P(x) true or false when the domain is empty?', ['false']),
    hard('logic', 'Which rule of inference goes from p → q and p to q?', ['modus ponens', 'modus ponens rule']),
    hard('logic', 'Which rule of inference goes from p → q and ¬q to ¬p?', ['modus tollens']),
    hard('logic', 'Which rule chains p → q and q → r to get p → r?', ['hypothetical syllogism', 'transitivity']),
    hard('logic', 'Which rule goes from p ∨ q and ¬p to q?', ['disjunctive syllogism', 'disjunctive syllogism rule']),
    hard('logic', 'Which rule combines p ∨ q and ¬p ∨ r into q ∨ r?', ['resolution']),
    hard('logic', 'Which fallacy argues from q and p → q to p?', ['affirming the consequent']),
    hard('logic', 'Which law says p ∨ (q ∧ r) equals (p ∨ q) ∧ (p ∨ r)?', ['distributive', 'distributive law']),
    hard('logic', 'Is NAND alone functionally complete?', ['yes', 'true']),
    hard('logic', 'In ¬p ∨ q, which symbol binds first?', ['¬', 'not', 'negation']),
    hard('logic', 'What is (p ∧ q) ∨ (p ∧ ¬q) equivalent to?', ['p', 'just p']),
    hard('logic', 'What is p ∨ (p ∧ q) by absorption?', ['p']),
    hard('logic', 'What is p ∧ (p ∨ q) by absorption?', ['p']),
    ...([1, 2, 3, 4].map((n) => num('logic', 'hard',
        `How many rows does a truth table for ${n} propositional variable${n === 1 ? '' : 's'} have?`,
        2 ** n, `${2 ** n} rows`))),
    num('logic', 'hard', 'How many different Boolean functions of 3 variables exist?', 2 ** (2 ** 3), '256'),
    num('logic', 'hard', 'How many different Boolean functions of 4 variables exist?', 2 ** (2 ** 4), '65536'),
    num('logic', 'hard', 'A truth table has 3 variables. How many rows produce a specific single assignment of all three?', 1),

    // ═══ Sets ════════════════════════════════════════════════════════════════
    easy('sets', 'What is the set containing every element of A and B called?', ['union', 'the union']),
    easy('sets', 'What is the set of common elements of A and B called?', ['intersection', 'the intersection']),
    easy('sets', 'What is the set of elements in A but not in B called?', ['difference', 'set difference', 'relative complement']),
    easy('sets', 'What is another name for the set with no elements?', ['empty set', 'null set', 'void set', '∅']),
    easy('sets', 'What does A ⊆ B mean?', ['a is a subset of b', 'every element of a is in b', 'subset']),
    easy('sets', 'What is the set of all subsets of A called?', ['power set', 'the power set']),
    easy('sets', 'What does A × B contain?', ['ordered pairs', 'all ordered pairs', 'pairs (a, b)']),
    easy('sets', 'What are two sets with no common elements called?', ['disjoint', 'disjoint sets']),
    easy('sets', 'What does the complement of A contain (within the universe)?', ['everything not in a', 'elements not in a', 'everything outside a']),
    easy('sets', 'How many elements does the power set of the empty set have?', ['1', 'one']),
    easy('sets', 'What is A ∪ ∅?', ['a', 'the set a']),
    easy('sets', 'What is A ∩ ∅?', ['empty set', '∅', 'the empty set']),
    easy('sets', 'Which operation keeps elements in exactly one of A and B?', ['symmetric difference', 'symmetric-difference', 'xor']),
    hard('sets', 'Which law says A ∪ (B ∩ C) = (A ∪ B) ∩ (A ∪ C)?', ['distributive', 'distributive law']),
    hard('sets', 'What does the inclusion–exclusion principle give for two sets?', ['|a| + |b| − |a∩b|', 'a+b-a∩b', 'a plus b minus intersection']),
    hard('sets', 'What is |A ∪ B ∪ C| through inclusion–exclusion?', ['|a|+|b|+|c|−|a∩b|−|a∩c|−|b∩c|+|a∩b∩c|', 'sum minus pair intersections plus triple']),
    num('sets', 'hard', 'If |A| = 3 and |B| = 4, how many elements does A × B have?', 12),
    num('sets', 'hard', 'If |A| = 5, how many ordered pairs are in A × A?', 25),
    hard('sets', 'Is the empty set a subset of every set?', ['yes', 'true']),
    hard('sets', 'What is the intersection of a set with its complement?', ['∅', 'empty set', 'the empty set']),
    hard('sets', 'What is the union of a set with its complement?', ['universe', 'u', 'the universe']),
    ...([3, 4, 5, 6, 7, 8, 10].map((n) => num('sets', 'hard',
        `How many subsets does a set with ${n} elements have?`, 2 ** n))),
    ...([3, 5, 6, 7].map((n) => num('sets', 'hard',
        `How many proper subsets does a set with ${n} elements have?`, 2 ** n - 1))),
    ...([3, 4, 5, 6].map((n) => num('sets', 'hard',
        `How many non-empty subsets does a set with ${n} elements have?`, 2 ** n - 1))),
    num('sets', 'hard', 'A and B are sets with |A| = 20 and |B| = 15 and |A ∩ B| = 8. What is |A ∪ B|?', 20 + 15 - 8),
    num('sets', 'hard', 'A and B are sets with |A| = 42 and |B| = 27 and |A ∪ B| = 55. What is |A ∩ B|?', 42 + 27 - 55),
    num('sets', 'hard', 'In a class of 40, 25 take maths, 20 take physics and 12 take both. How many take neither?', 40 - (25 + 20 - 12)),
    num('sets', 'hard', 'A set has 6 elements. How many subsets of size 2 does it have?', binom(6, 2)),
    num('sets', 'hard', 'A set has 7 elements. How many subsets of size 3 does it have?', binom(7, 3)),
    num('sets', 'hard', 'Three sets have |A| = 10, |B| = 12, |C| = 8 with |A∩B| = 4, |A∩C| = 3, |B∩C| = 5 and |A∩B∩C| = 2. What is |A ∪ B ∪ C|?', 10 + 12 + 8 - 4 - 3 - 5 + 2),

    // ═══ Relations & functions ═══════════════════════════════════════════════
    easy('relfun', 'What is a relation on a set A formally defined as?', ['a subset of a × a', 'subset of a×a', 'subset of the cartesian product']),
    easy('relfun', 'What does a relation being reflexive require?', ['(a,a) in r for every a', 'every element relates to itself', 'a r a for all a']),
    easy('relfun', 'What does a relation being symmetric require?', ['a r b implies b r a', 'if a relates to b then b relates to a', 'both directions']),
    easy('relfun', 'What does a relation being transitive require?', ['a r b and b r c imply a r c', 'chains can be shortened', 'a to b and b to c give a to c']),
    easy('relfun', 'What does a relation being antisymmetric require?', ['a r b and b r a imply a = b', 'the only two-way pairs are equal elements']),
    easy('relfun', 'What is a reflexive, symmetric, transitive relation called?', ['equivalence relation', 'equivalence']),
    easy('relfun', 'What is a reflexive, antisymmetric, transitive relation called?', ['partial order', 'partial ordering', 'poset']),
    easy('relfun', 'What is another name for the inverse of a function?', ['inverse relation', 'the inverse']),
    easy('relfun', 'What is a function that is both injective and surjective called?', ['bijective', 'bijection', 'one to one and onto']),
    easy('relfun', 'What is a function that is injective called in plain English?', ['one to one', 'one-to-one', 'one-to-one function']),
    easy('relfun', 'What is a function that is surjective called in plain English?', ['onto', 'onto function']),
    easy('relfun', 'What is the set of actual outputs of a function called?', ['range', 'image', 'the range']),
    easy('relfun', 'What is the set of allowed inputs of a function called?', ['domain', 'the domain']),
    easy('relfun', 'What is the pair (a, b) in a relation often written as?', ['a r b', 'arb', 'a relates to b']),
    easy('relfun', 'What is the relation "divides" on the positive integers a classic example of?', ['partial order', 'poset']),
    hard('relfun', 'Why is "less than or equal to" not an equivalence relation?', ['not symmetric', 'it is antisymmetric']),
    hard('relfun', 'What does a bijection between two finite sets prove about their sizes?', ['equal', 'same size', 'they are equal']),
    hard('relfun', 'What is the composition of f then g written as?', ['g ∘ f', 'g(f(x))', 'g of f']),
    num('relfun', 'hard', 'How many relations are there on a set with 2 elements?', 2 ** 4, '16'),
    num('relfun', 'hard', 'How many relations are there on a set with 3 elements?', 2 ** 9, '512'),
    num('relfun', 'hard', 'How many reflexive relations are there on a set with 3 elements?', 2 ** (9 - 3), '64'),
    num('relfun', 'hard', 'How many symmetric relations are there on a set with 3 elements?', 2 ** 6, '64'),
    num('relfun', 'hard', 'How many functions are there from a 3-element set to a 2-element set?', 2 ** 3, '8'),
    num('relfun', 'hard', 'How many functions are there from a 2-element set to a 5-element set?', 5 ** 2, '25'),
    num('relfun', 'hard', 'How many bijections are there from a 4-element set to itself?', fact(4)),
    num('relfun', 'hard', 'How many injections are there from a 2-element set into a 5-element set?', perm(5, 2)),
    num('relfun', 'hard', 'How many injections are there from a 3-element set into a 5-element set?', perm(5, 3)),
    hard('relfun', 'Can a function from a 4-element set to a 3-element set be injective?', ['no', 'false']),
    hard('relfun', 'Can a function from a 3-element set to a 4-element set be surjective?', ['no', 'false']),
    hard('relfun', 'What is the pigeonhole principle in one line?', ['more items than boxes forces a collision', 'two items share a box', 'some box holds two']),
    hard('relfun', 'How many elements must you pick from 10 elements to guarantee two are the same?', ['11', 'eleven']),
    hard('relfun', 'What is the equivalence class of an element under an equivalence relation?', ['all elements related to it', 'its partners', 'the set of elements it relates to']),
    num('relfun', 'hard', 'How many relations are there on a set with 4 elements?', 2 ** 16, '65536'),
    num('relfun', 'hard', 'How many reflexive relations are there on a set with 5 elements (2^(n²−n))?', 2 ** (25 - 5)),
    num('relfun', 'hard', 'How many symmetric relations are there on a set with 4 elements (2^(n(n+1)/2))?', 2 ** (4 * 5 / 2)),
    num('relfun', 'hard', 'How many functions are there from a 5-element set to a 3-element set?', 3 ** 5),
    num('relfun', 'hard', 'How many bijections are there from a 6-element set to itself?', fact(6)),

    // ═══ Counting & combinatorics ════════════════════════════════════════════
    easy('counting', 'What does n! count?', ['arrangements of n items', 'permutations of n items', 'orders', 'ways to arrange n things']),
    easy('counting', 'What does C(n, r) count?', ['subsets', 'choices without order', 'combinations']),
    easy('counting', 'What does P(n, r) count?', ['ordered selections', 'permutations', 'arrangements with order']),
    easy('counting', 'What is 0!?', ['1', 'one']),
    num('counting', 'easy', 'In how many orders can 4 distinct books sit on a shelf?', fact(4)),
    num('counting', 'easy', 'How many ways can you choose 2 toppings from 5?', binom(5, 2)),
    num('counting', 'easy', 'How many 3-letter words can be made from 26 letters with repetition allowed?', 26 ** 3, '17576'),
    num('counting', 'easy', 'How many outcomes does tossing 4 fair coins have?', 2 ** 4, '16'),
    num('counting', 'easy', 'How many 4-bit binary strings are there?', 2 ** 4, '16'),
    num('counting', 'easy', 'What is the sum of the entries in row 4 of Pascal’s triangle (starting with row 0)?', 2 ** 4, '16'),
    easy('counting', 'How many ways can a 5-person committee pick a chair?', ['5', 'five']),
    easy('counting', 'What does the multiplication principle say about consecutive independent choices?', ['multiply the counts', 'multiply', 'multiply them']),
    num('counting', 'hard', 'In how many ways can 6 distinct people be seated in a row?', fact(6)),
    num('counting', 'hard', 'How many ways can a committee of 3 be chosen from 8 people?', binom(8, 3)),
    num('counting', 'hard', 'How many ways can 3 people finish first, second and third out of 10 runners?', perm(10, 3)),
    num('counting', 'hard', 'How many ways can 5 identical candies go to 3 children?', starsBars(3, 5)),
    num('counting', 'hard', 'How many non-negative integer solutions does x + y + z = 7 have?', starsBars(3, 7)),
    num('counting', 'hard', 'How many non-negative integer solutions does x + y + z + w = 6 have?', starsBars(4, 6)),
    num('counting', 'hard', 'In how many orders can 5 people sit around a round table (rotations identical)?', circularPerm(5)),
    num('counting', 'hard', 'How many 8-bit strings contain exactly three 1s?', binom(8, 3)),
    num('counting', 'hard', 'How many 6-bit strings contain exactly two 1s?', binom(6, 2)),
    num('counting', 'hard', 'How many paths move 4 steps right and 3 steps up on a grid?', binom(4 + 3, 4)),
    num('counting', 'hard', 'How many paths move 5 right and 5 up on a grid?', binom(10, 5)),
    num('counting', 'hard', 'How many handshakes happen when 10 people each shake every other hand once?', binom(10, 2)),
    num('counting', 'hard', 'How many edges does the complete graph on 8 vertices have?', binom(8, 2)),
    num('counting', 'hard', 'How many ways can 2 red and 2 blue identical balls be arranged in a row?', binom(4, 2)),
    num('counting', 'hard', 'What is the coefficient of x³ in (1 + x)⁷?', binom(7, 3)),
    num('counting', 'hard', 'What is the coefficient of x²y³ in (x + y)⁵?', binom(5, 2)),
    num('counting', 'hard', 'How many diagonals does a convex octagon have?', 8 * (8 - 3) / 2),
    num('counting', 'hard', 'How many diagonals does a convex decagon have?', 10 * (10 - 3) / 2),
    num('counting', 'hard', 'How many subsets of size 4 can be formed from a 9-element set?', binom(9, 4)),
    num('counting', 'hard', 'How many strings of 4 letters from {a, b, c} are there with repetition allowed?', 3 ** 4, '81'),
    num('counting', 'hard', 'How many 4-digit PINs can be made from the digits 0-9 if repetition is allowed?', 10 ** 4, '10000'),
    num('counting', 'hard', 'How many 3-character codes can be made from 10 distinct symbols with no repetition?', perm(10, 3)),
    num('counting', 'hard', 'What is the minimum number of people needed to guarantee two share a birth month?', 13),
    num('counting', 'hard', 'What is the fewest number of cards to draw from a 52-card deck to guarantee two of the same suit?', 5),
    hard('counting', 'What does C(n, 0) equal?', ['1', 'one']),
    hard('counting', 'What does C(n, n) equal?', ['1', 'one']),
    hard('counting', 'Which identity says C(n, r) = C(n − 1, r − 1) + C(n − 1, r)?', ['pascal', 'pascal’s identity', "pascal's identity", 'pascal’s rule']),
    num('counting', 'hard', 'What is 7!?', fact(7)),
    num('counting', 'hard', 'What is 9!?', fact(9)),
    num('counting', 'hard', 'In how many ways can 7 people line up?', fact(7)),
    num('counting', 'hard', 'In how many ways can a president and a treasurer be picked from 12 people (different people)?', perm(12, 2)),
    num('counting', 'hard', 'How many 5-card hands can be dealt from a 52-card deck?', binom(52, 5)),
    num('counting', 'hard', 'How many ways can a committee of 4 be chosen from 10 people?', binom(10, 4)),
    num('counting', 'hard', 'How many bit strings of length 10 have exactly 4 ones?', binom(10, 4)),
    num('counting', 'hard', 'How many ways can 10 identical coins be split among 4 children?', starsBars(4, 10)),
    num('counting', 'hard', 'In how many ways can 6 people sit around a round table?', circularPerm(6)),
    num('counting', 'hard', 'How many paths go 6 steps right and 2 steps up on a grid?', binom(8, 2)),

    // ═══ Number theory & modular arithmetic ══════════════════════════════════
    easy('numtheory', 'What is a number with exactly two positive divisors called?', ['prime', 'a prime', 'prime number']),
    easy('numtheory', 'Is 1 prime?', ['no', 'false']),
    easy('numtheory', 'Is 2 prime?', ['yes', 'true']),
    easy('numtheory', 'What is the greatest common divisor of two coprime numbers?', ['1', 'one']),
    easy('numtheory', 'What does a ≡ b (mod m) mean?', ['m divides a − b', 'a and b leave the same remainder', 'same remainder mod m']),
    num('numtheory', 'easy', 'What is 15 mod 4?', 15 % 4),
    num('numtheory', 'easy', 'What is 100 mod 7?', 100 % 7),
    easy('numtheory', 'Which primes divide 91?', ['7 and 13', '7, 13', '7 13']),
    num('numtheory', 'easy', 'What is the decimal value of binary 1011?', 11),
    num('numtheory', 'easy', 'What is the decimal value of binary 11111?', 31),
    easy('numtheory', 'Write 9 in binary.', ['1001']),
    easy('numtheory', 'What is the hexadecimal value of decimal 255?', ['ff', 'FF', 'ffh', '0xff']),
    easy('numtheory', 'Which digits make a number divisible by 3?', ['the digits sum to a multiple of 3', 'digit sum divisible by 3', 'sum of digits divisible by 3']),
    easy('numtheory', 'Which digit makes a number divisible by 5?', ['0 or 5', '0 and 5', '0, 5']),
    hard('numtheory', 'What is the Euclidean algorithm based on?', ['gcd(a,b) = gcd(b, a mod b)', 'repeat with the remainder', 'gcd(a, b) = gcd(b, a mod b)']),
    hard('numtheory', 'What is Bézout’s identity?', ['gcd is a linear combination', 'gcd(a,b) = ax + by', 'gcd as ax+by']),
    hard('numtheory', 'What does Fermat’s little theorem say for prime p not dividing a?', ['a^(p−1) ≡ 1 mod p', 'a^(p-1) = 1 mod p']),
    hard('numtheory', 'What is Euler’s theorem a generalisation of?', ['fermat’s little theorem', 'fermat']),
    hard('numtheory', 'When does a modular inverse of a modulo m exist?', ['gcd(a, m) = 1', 'when a and m are coprime', 'coprime']),
    hard('numtheory', 'What is the smallest positive integer congruent to 3 mod 7 that is greater than 20?', ['24']),
    num('numtheory', 'hard', 'What is the remainder when 2^10 is divided by 1000?', 1024 % 1000),
    hard('numtheory', 'What is the last digit of 7^4?', ['1', 'one']),
    hard('numtheory', 'What does the Chinese Remainder Theorem solve?', ['simultaneous congruences', 'a system of congruences', 'systems of congruences']),
    hard('numtheory', 'Which integers have a multiplicative inverse modulo 6?', ['1 and 5', '1, 5', '1 5']),
    hard('numtheory', 'What is the prime factorisation of 60?', ['2^2 × 3 × 5', '2^2*3*5', '2²×3×5', '2, 2, 3, 5']),
    hard('numtheory', 'What is the prime factorisation of 360?', ['2^3 × 3^2 × 5', '2^3*3^2*5', '2³×3²×5']),
    num('numtheory', 'hard', 'How many primes are there below 20?', 8),
    num('numtheory', 'hard', 'What is the largest prime below 30?', 29),
    num('numtheory', 'hard', 'What is the sum of the first four primes?', 2 + 3 + 5 + 7),
    num('numtheory', 'hard', 'What is the smallest composite number?', 4),
    hard('numtheory', 'Why is 1 not prime?', ['it has only one divisor', 'primes need two divisors', 'one divisor']),
    ...([4, 6, 8, 9, 10, 12, 14, 15, 18, 20, 24, 30].map((n) => num('numtheory', 'hard',
        `What is φ(${n}), the number of integers from 1 to ${n} coprime to ${n}?`, phi(n)))),
    ...([12, 18].map((a) => num('numtheory', 'hard', `What is gcd(${a}, 30)?`, gcd(a, 30)))),
    num('numtheory', 'hard', 'What is lcm(12, 18)?', lcm(12, 18)),
    num('numtheory', 'hard', 'What is lcm(8, 14)?', lcm(8, 14)),
    num('numtheory', 'hard', 'What is 3⁵ mod 7?', modPow(3, 5, 7)),
    num('numtheory', 'hard', 'What is 2^10 mod 11?', modPow(2, 10, 11)),
    num('numtheory', 'hard', 'What is 7^5 mod 13?', modPow(7, 5, 13)),
    num('numtheory', 'hard', 'Write 200 in binary.', toBin(200)),
    num('numtheory', 'hard', 'Write 255 in binary.', toBin(255)),
    num('numtheory', 'hard', 'What is the hexadecimal value of decimal 200?', toHex(200), toHex(200).toLowerCase()),
    num('numtheory', 'hard', 'What is 1234 mod 97?', 1234 % 97),
    num('numtheory', 'hard', 'What is the multiplicative inverse of 3 modulo 7?', 5),
    num('numtheory', 'hard', 'What is the multiplicative inverse of 5 modulo 11?', 9),
    num('numtheory', 'hard', 'How many steps does Euclid’s algorithm take for gcd(48, 18)?', 3),
    num('numtheory', 'hard', 'What is 6·7 mod 5?', (6 * 7) % 5),

    // ═══ Sequences, series & recurrences ═════════════════════════════════════
    easy('sequences', 'What is an = an−1 + d called?', ['arithmetic sequence', 'arithmetic progression', 'ap']),
    easy('sequences', 'What is an = r·an−1 called?', ['geometric sequence', 'geometric progression', 'gp']),
    num('sequences', 'easy', 'What is the common difference in 5, 9, 13, 17?', 4),
    num('sequences', 'easy', 'What is the common ratio in 3, 6, 12, 24?', 2),
    num('sequences', 'easy', 'What is the 4th term of 2, 5, 8, 11?', arith(2, 3, 4)),
    num('sequences', 'easy', 'What is the next term of 1, 4, 9, 16?', 25),
    num('sequences', 'easy', 'What is the next term of 1, 1, 2, 3, 5, 8?', fib(7)),
    easy('sequences', 'What is Σ from 1 to n of k equal to?', ['n(n+1)/2', 'n(n + 1)/2', 'n(n+1)/2']),
    easy('sequences', 'What is the sum of the first n odd numbers?', ['n²', 'n^2', 'n2']),
    easy('sequences', 'Which powerful proof technique proves a statement for all n?', ['induction', 'mathematical induction']),
    easy('sequences', 'What is the induction step also called?', ['inductive step', 'the inductive step']),
    num('sequences', 'hard', 'What is the 10th term of 7, 11, 15, …?', arith(7, 4, 10)),
    num('sequences', 'hard', 'What is the 6th term of 3, 6, 12, 24, …?', geom(3, 2, 6)),
    num('sequences', 'hard', 'What is the sum 1 + 2 + … + 100?', sumTo(100)),
    num('sequences', 'hard', 'What is the sum of the squares 1² + 2² + … + 10²?', sumSquares(10)),
    num('sequences', 'hard', 'What is the sum of the cubes 1³ + 2³ + 3³ + 4³?', sumCubes(4)),
    num('sequences', 'hard', 'What is the sum of the first 20 positive integers?', sumTo(20)),
    num('sequences', 'hard', 'What is the sum of the first 5 terms of 2 + 4 + 8 + …?', geomSum(2, 2, 5)),
    num('sequences', 'hard', 'What is the sum of the first 4 terms of 1 + 3 + 9 + …?', geomSum(1, 3, 4)),
    num('sequences', 'hard', 'What is the sum of 1/3 + 1/9 + 1/27 + …?', frac(1, 2), 0.5),
    hard('sequences', 'What is the closed form of an = 2·an−1 with a1 = 3?', ['3·2^(n−1)', '3*2^(n-1)', '3 × 2^(n-1)']),
    hard('sequences', 'What is the characteristic equation of an = 5an−1 − 6an−2?', ['r² − 5r + 6 = 0', 'r^2 - 5r + 6 = 0', 'r2−5r+6=0']),
    hard('sequences', 'What are the roots of r² − 5r + 6 = 0?', ['2 and 3', '2, 3', '2 3']),
    hard('sequences', 'What is a recurrence relation?', ['a term defined by earlier terms', 'defines a term from previous ones', 'term depends on previous terms']),
    hard('sequences', 'What does a telescoping sum do?', ['most terms cancel', 'cancels intermediate terms', 'cancellation']),
    hard('sequences', 'What is Σ from 1 to n of 1/(k(k+1))?', ['n/(n+1)', 'n/(n + 1)']),
    hard('sequences', 'Which sequence satisfies an = an−1 + an−2 with a1 = a2 = 1?', ['fibonacci', 'the fibonacci sequence']),
    num('sequences', 'hard', 'What is the sum of the first 6 Fibonacci numbers with F1 = F2 = 1?', [1, 1, 2, 3, 5, 8].reduce((a, b) => a + b, 0)),
    hard('sequences', 'What is the ratio between consecutive Fibonacci numbers as n grows?', ['golden ratio', 'φ', '1.618']),
    num('sequences', 'hard', 'What is a1 of the arithmetic sequence with a5 = 20 and d = 3?', arith(20, -3, 5 - 4)),
    num('sequences', 'hard', 'What is the 12th term of 4, 9, 14, …?', arith(4, 5, 12)),
    num('sequences', 'hard', 'What is the 8th term of 2, 6, 18, …?', geom(2, 3, 8)),
    num('sequences', 'hard', 'What is the sum of the first 15 positive integers?', sumTo(15)),
    num('sequences', 'hard', 'What is the sum 1² + 2² + … + 12²?', sumSquares(12)),
    num('sequences', 'hard', 'What is the sum 1³ + 2³ + … + 5³?', sumCubes(5)),
    num('sequences', 'hard', 'What is F10 with F1 = F2 = 1?', fib(10)),
    num('sequences', 'hard', 'What is F12 with F1 = F2 = 1?', fib(12)),
    num('sequences', 'hard', 'What is the sum of the first 10 terms of 1 + 2 + 4 + 8 + …?', geomSum(1, 2, 10)),
    num('sequences', 'hard', 'What is the sum of the first 6 terms of 3 + 9 + 27 + …?', geomSum(3, 3, 6)),

    // ═══ Graph theory & trees ════════════════════════════════════════════════
    easy('graphs', 'How many edges does the complete graph Kn have?', ['n(n−1)/2', 'n(n-1)/2', 'c(n,2)']),
    easy('graphs', 'What is the handshaking lemma?', ['sum of degrees = 2 × edges', 'degrees sum to twice the edges', 'sum deg = 2e']),
    easy('graphs', 'How many edges does a tree with n vertices have?', ['n − 1', 'n-1', 'n−1']),
    easy('graphs', 'What is a connected acyclic graph called?', ['tree', 'a tree']),
    easy('graphs', 'What is a graph whose vertices can be split into two independent sets called?', ['bipartite']),
    easy('graphs', 'How many colours are enough for the edges of a bipartite graph?', ['2', 'two']),
    easy('graphs', 'What is a closed walk with no repeated edges called?', ['cycle', 'circuit']),
    easy('graphs', 'What is the degree of a vertex in a cycle graph Cn?', ['2', 'two']),
    easy('graphs', 'How many edges does the cycle graph Cn have?', ['n']),
    easy('graphs', 'What is a spanning tree?', ['a tree including all vertices', 'tree covering every vertex', 'acyclic spanning subgraph']),
    easy('graphs', 'How many edges does a spanning tree of a graph with n vertices have?', ['n − 1', 'n-1']),
    hard('graphs', 'When does an undirected graph have an Euler circuit?', ['all degrees even and connected', 'every vertex has even degree', 'all even degrees']),
    hard('graphs', 'When does a graph have an Euler path but no circuit?', ['exactly two odd vertices', 'two odd degrees', 'exactly 2 odd']),
    hard('graphs', 'What does Euler’s formula state for a connected planar graph?', ['v − e + f = 2', 'v-e+f=2', 'v − e + f = 2']),
    hard('graphs', 'Which theorem bounds the chromatic number of a planar graph?', ['four colour theorem', '4 colour theorem', 'four color theorem']),
    hard('graphs', 'What is the chromatic number of a cycle of odd length?', ['3', 'three']),
    hard('graphs', 'What is the chromatic number of the complete graph K4?', ['4', 'four']),
    hard('graphs', 'What is the chromatic number of K5?', ['5', 'five']),
    hard('graphs', 'What is the chromatic number of a bipartite graph with at least one edge?', ['2', 'two']),
    num('graphs', 'hard', 'How many spanning trees does a complete graph K3 have?', 3),
    hard('graphs', 'Which graph has every vertex of the same degree?', ['regular', 'regular graph']),
    num('graphs', 'hard', 'What is the degree sum of a 3-regular graph with 6 vertices?', 18),
    hard('graphs', 'Which necessary condition rules out an Euler circuit immediately?', ['an odd degree vertex', 'odd degree', 'any vertex with odd degree']),
    hard('graphs', 'What does a connected graph with n − 1 edges and no cycle necessarily look like?', ['a tree']),
    hard('graphs', 'What does the degree sequence of a tree with n ≥ 2 vertices sum to?', ['2(n − 1)', '2(n-1)', 'twice n minus one']),
    num('graphs', 'hard', 'What is the maximum number of edges in a simple graph on 12 vertices?', binom(12, 2)),
    num('graphs', 'hard', 'What is the maximum number of edges in a bipartite graph with parts of size 5 and 6?', 30),
    num('graphs', 'hard', 'How many faces does a connected planar graph with 8 vertices and 12 edges have?', 2 - 8 + 12),
    ...([3, 5, 6, 7, 8, 9, 10].map((n) => num('graphs', 'hard',
        `Kn is the complete graph on ${n} vertices. How many edges does it have?`, binom(n, 2)))),
    ...([2, 3, 4, 5, 6, 10].map((n) => num('graphs', 'hard',
        `How many edges do the 2-regular cycle graphs on ${n} vertices have?`, n))),
    num('graphs', 'hard', 'A tree has 15 vertices. How many edges does it have?', 15 - 1),
    num('graphs', 'hard', 'A graph has 20 edges. What does the sum of all vertex degrees equal?', 40),
    num('graphs', 'hard', 'A 3-regular graph has 8 vertices. How many edges does it have?', (3 * 8) / 2),
    num('graphs', 'hard', 'A 4-regular graph has 10 vertices. How many edges does it have?', (4 * 10) / 2),
    num('graphs', 'hard', 'A connected planar graph has 10 vertices and 14 edges. How many faces does Euler’s formula give?', 2 - 10 + 14),
    num('graphs', 'hard', 'How many edges does a spanning tree of a graph with 25 vertices have?', 24),
    num('graphs', 'hard', 'How many colours does K6 need?', 6),

    // ═══ Boolean algebra & logic gates ═══════════════════════════════════════
    easy('boolalg', 'Which gate outputs 1 when at least one input is 1?', ['or', 'or gate']),
    easy('boolalg', 'Which gate outputs the opposite of its input?', ['not', 'inverter', 'not gate']),
    easy('boolalg', 'What is 0 AND 0?', ['0', 'zero']),
    easy('boolalg', 'What is 0 OR 0?', ['0', 'zero']),
    easy('boolalg', 'What is 1 AND 1?', ['1', 'one']),
    easy('boolalg', 'What is 1 OR 0?', ['1', 'one']),
    easy('boolalg', 'What is NOT 0?', ['1', 'one']),
    easy('boolalg', 'What is 0 XOR 1?', ['1', 'one']),
    easy('boolalg', 'Which gate is an AND followed by NOT?', ['nand', 'nand gate']),
    easy('boolalg', 'Which algebra works with the values 0 and 1 and the operators + and ·?', ['boolean algebra', 'boolean']),
    easy('boolalg', 'In Boolean algebra, what does A · 1 equal?', ['a']),
    easy('boolalg', 'In Boolean algebra, what does A + 1 equal?', ['1']),
    easy('boolalg', 'In Boolean algebra, what does A + 0 equal?', ['a']),
    easy('boolalg', 'In Boolean algebra, what does A · 0 equal?', ['0', 'zero']),
    hard('boolalg', 'What does A + A′ equal?', ['1', 'one']),
    hard('boolalg', 'What does A · A′ equal?', ['0', 'zero']),
    hard('boolalg', 'What is the dual of A + B · C?', ['a · (b + c)', 'a·(b+c)', 'a and (b or c)']),
    hard('boolalg', 'Which gate set is functionally complete on its own apart from NAND?', ['nor', 'nor gates', 'nor gate']),
    num('boolalg', 'hard', 'How many minterms does a 3-variable Boolean function have?', 2 ** 3, '8'),
    num('boolalg', 'hard', 'How many cells does a 4-variable Karnaugh map have?', 2 ** 4, '16'),
    num('boolalg', 'hard', 'How many cells does a 3-variable Karnaugh map have?', 8),
    hard('boolalg', 'What is the simplified form of A·B + A·B′?', ['a']),
    hard('boolalg', 'What is the simplified form of (A + B)·(A + B′)?', ['a']),
    hard('boolalg', 'What is the simplified form of A + A′·B?', ['a + b', 'a+b']),
    hard('boolalg', 'What form is a sum of minterms called?', ['canonical sum of products', 'sum of products', 'dnf', 'disjunctive normal form']),
    hard('boolalg', 'What form is a product of maxterms called?', ['product of sums', 'cnf', 'conjunctive normal form', 'canonical product of sums']),
    hard('boolalg', 'Which two gates make a half adder?', ['xor and and', 'xor, and', 'an xor and an and']),
    hard('boolalg', 'What is the carry output of a half adder?', ['a and b', 'a·b', 'ab']),
    hard('boolalg', 'What is the sum output of a half adder?', ['a xor b', 'a⊕b', 'a xor b']),
    hard('boolalg', 'How many inputs does a full adder take?', ['3', 'three']),
    hard('boolalg', 'Which theorem lets you push a NOT through AND and OR?', ['de morgan', 'de morgan’s theorem', 'demorgan']),
    hard('boolalg', 'What is the dual of A · 1 = A?', ['a + 0 = a', 'a+0=a']),
    num('boolalg', 'hard', 'How many rows does a 5-variable truth table have?', 2 ** 5),
    num('boolalg', 'hard', 'How many minterms does a 4-variable function have?', 2 ** 4),
    num('boolalg', 'hard', 'How many 3-input Boolean functions exist?', 2 ** 8),

    // ═══ Discrete probability ════════════════════════════════════════════════
    easy('prob', 'What is the probability of a certain event?', ['1', 'one', '100%']),
    easy('prob', 'What is the probability of an impossible event?', ['0', 'zero']),
    easy('prob', 'What is the probability of getting tails on one fair coin toss?', ['1/2', '0.5', '50%', 'half']),
    easy('prob', 'What is the probability of rolling an even number on a fair die?', ['1/2', '0.5', '50%', '3/6']),
    easy('prob', 'What is the probability of rolling a number greater than 4 on a fair die?', ['1/3', '2/6']),
    easy('prob', 'What is P(A′) in terms of P(A)?', ['1 − p(a)', '1-p(a)', 'one minus p(a)']),
    easy('prob', 'What is P(A ∪ B) when A and B are mutually exclusive?', ['p(a) + p(b)', 'p(a)+p(b)', 'the sum of the probabilities']),
    num('prob', 'easy', 'How many outcomes does tossing 3 coins have?', 8),
    easy('prob', 'What is the expected value of one fair six-sided die?', ['3.5', '7/2', '3 1/2']),
    easy('prob', 'What is the expected number of heads in one fair coin toss?', ['0.5', '1/2', 'half']),
    hard('prob', 'What does it mean for two events to be independent?', ['p(a∩b) = p(a)p(b)', 'one does not affect the other', 'p(a and b) = p(a)p(b)']),
    hard('prob', 'What is P(A | B) equal to?', ['p(a∩b)/p(b)', 'p(a and b)/p(b)', 'p(a∩b) / p(b)']),
    hard('prob', 'What does Bayes’ theorem compute?', ['p(a | b) from p(b | a)', 'the reverse conditional', 'a posterior probability']),
    num('prob', 'hard', 'What is the probability of rolling a sum of 7 with two dice?', countDice(([a, b]) => a + b === 7) / DICE.length, '6/36'),
    num('prob', 'hard', 'What is the probability of rolling a sum of 12 with two dice?', countDice(([a, b]) => a + b === 12) / DICE.length, '1/36'),
    num('prob', 'hard', 'What is the probability of rolling a sum of 4 with two dice?', countDice(([a, b]) => a + b === 4) / DICE.length, '3/36'),
    num('prob', 'hard', 'What is the probability of rolling a sum of 9 with two dice?', countDice(([a, b]) => a + b === 9) / DICE.length, '4/36'),
    num('prob', 'hard', 'What is the probability of rolling a double with two dice?', countDice(([a, b]) => a === b) / DICE.length, '6/36'),
    num('prob', 'hard', 'What is the probability of at least one head in two fair coin tosses?', 3 / 4, '0.75'),
    num('prob', 'hard', 'What is the probability of exactly one head in two fair coin tosses?', 1 / 2, '2/4'),
    num('prob', 'hard', 'What is the probability of exactly two heads in three fair coin tosses?', TOSS3.filter((t) => t.filter((c) => c === 'H').length === 2).length / TOSS3.length, '3/8'),
    num('prob', 'hard', 'What is the probability of no heads in three fair coin tosses?', 1 / 8, '0.125'),
    num('prob', 'hard', 'What is the probability that a card drawn from 52 is a heart?', 13 / 52, '1/4', '0.25'),
    num('prob', 'hard', 'What is the probability that a card drawn from 52 is a face card (J, Q, K)?', 12 / 52, '3/13'),
    num('prob', 'hard', 'What is the probability that a card drawn from 52 is an ace or a king?', 8 / 52, '2/13'),
    num('prob', 'hard', 'What is the probability that a card drawn from 52 is red and a face card?', 6 / 52, '3/26'),
    num('prob', 'hard', 'What is the expected number of heads in 10 fair coin tosses?', 5),
    num('prob', 'hard', 'What is the expected value of two fair dice summed?', 7),
    num('prob', 'hard', 'What is the probability of drawing two kings in a row without replacement from 52?', '4/52 × 3/51', '1/221'),
    num('prob', 'hard', 'What is the probability of two heads in a row with a fair coin?', 1 / 4, '0.25'),
    num('prob', 'hard', 'If P(A) = 0.4 and P(B) = 0.5 and the events are independent, what is P(A ∩ B)?', 0.2, '1/5'),
    num('prob', 'hard', 'If P(A) = 0.3, P(B) = 0.4 and P(A ∩ B) = 0.1, what is P(A ∪ B)?', 0.6, '3/5'),
    num('prob', 'hard', 'If P(A) = 0.7, what is P(A′)?', 0.3, '3/10'),
    num('prob', 'hard', 'A family has two children. Given at least one is a boy, what is P(both boys) assuming equal likelihoods?', '1/3', '0.3333'),
    num('prob', 'hard', 'How many outcomes are in the sample space of rolling three dice?', 6 ** 3),
    num('prob', 'hard', 'How many outcomes are in the sample space of tossing 5 coins?', 2 ** 5),
    num('prob', 'hard', 'A bag holds 4 red and 6 blue balls. How many ways can you draw 2 balls?', binom(10, 2)),
    num('prob', 'hard', 'A bag holds 5 red and 5 blue balls. What is the probability of drawing red then blue without replacement?', frac(5 * 5, 10 * 9), 25 / 90),
]);
